name: Build Container Image and Push to Azure Function

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest 
    steps:

    - uses: actions/checkout@v2
    
    - uses: azure/docker-login@v1
      with:
        login-server: newtestdemo.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t newtestdemo.azurecr.io/myapp1:latest
        docker push newtestdemo.azurecr.io/myapp1:latest
        
    - name: Deploy Docker image to Azure Function App
      uses: azure/webapps-container-deploy@v1
      with:
        app-name: new-test-demo
        images: newtestdemo.azurecr.io/myapp1:latest
        resource-group: new-test-demo_group
        
    - name: Deploy into azure funtions
      uses: Azure/functions-action@v1
      with:
        app-name: testing0101
        package: 'newtestdemo.azurecr.io/myapp1:latest'

